### ISSUE TITLE
mat4 Cannot find module 'common'

### ISSUE THREAD

**Issue by Lehani** [toji/gl-matrix#160]
Error: Cannot find module 'common'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (...\node_modules\gl-matrix-mat4\index.js:29:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

var GLMAT_ARRAY_TYPE = require('common').GLMAT_ARRAY_TYPE;
var GLMAT_EPSILON = require('common').GLMAT_EPSILON;

need change to 

var GLMAT_ARRAY_TYPE = require('gl-matrix-common').GLMAT_ARRAY_TYPE;
var GLMAT_EPSILON = require('gl-matrix-common').GLMAT_EPSILON;

**Comment by toji** [comment]
I've just reworked the library a bit and pushed version 2.3.0 to npm. Please give it a try and see if it corrects this problem for you.

**Comment by Lehani** [comment]
Thanks. Everything works fine.
Before I installed the module from npm
https://www.npmjs.com/package/gl-matrix-mat4
