### ISSUE TITLE
 ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ouyangzhigang** [toji/gl-matrix#311]
nodejs-dashboard -- node -r nodejs-dashboard web-test-server.js
E:\nodejs\npm-global\node_modules\nodejs-dashboard\node_modules\_gl-matrix@2.6.0@gl-matrix\dist\gl-matrix.js:38
})(window, function() {
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (E:\nodejs\npm-global\node_modules\nodejs-dashboard\node_modules\_gl-matrix@2.6.0@gl-matrix\dist\gl-matrix.js:38:4)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\nodejs\npm-global\node_modules\nodejs-dashboard\node_modules\_drawille-canvas-blessed-contrib@0.1.3@drawille-canvas-blessed-contrib\index.js:3:16)
    at Module._compile (module.js:577:32)

**Comment by stefnotch** [comment]
https://github.com/toji/gl-matrix/issues/310
^Same issue

@andrevenancio Looks like the PR did cause some issues?

**Comment by stefnotch** [comment]
https://github.com/toji/gl-matrix/blob/e5b9a08ee61967dfa852d69f2d96d3c606767e64/dist/gl-matrix.js#L38

`window` used to be `this`

**Comment by andrevenancio** [comment]
Hey @stefnotch as I comment on #310 the module has been there since version 2.4.0.

However I've noticed there's a [bug](https://github.com/webpack/webpack/issues/6522) being reported in webpack github. Bare with me, I'll sort out a quick fix until they fix their bug

**Comment by stefnotch** [comment]
This is hopefully fixed now.
