### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by AshleyScirra** [toji/gl-matrix#349]
I can't get a build to work. Downloading 2.8.1 with node 11.4.0 and running the build instructions fails on `npm run build-all` with:

```
> gl-matrix@2.7.1 update-license-version C:\Users\AshleyTemp\Documents\GitHub\gl-matrix
> node utils/update-license-version.js

fs.js:135
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
```

This is preventing me working around #340 because the fix was never published.

**Comment by AshleyScirra** [comment]
`npm run build` also fails with:

```
C:\Users\AshleyTemp\Documents\GitHub\gl-matrix\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\AshleyTemp\Documents\GitHub\gl-matrix\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\AshleyTemp\Documents\GitHub\gl-matrix\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\AshleyTemp\Documents\GitHub\gl-matrix\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by stefnotch** [comment]
Ok, published it.
